### ISSUE TITLE
`undefined`s not stated

### ISSUE THREAD

**Issue by chpio** [qjebbs/sketch.d.ts#1]
Hi,

`undefined`s types seem to be missing in this lib.

For example, the `getSelectedDocument` function docs reads as:

> The selected Document or undefined if no document is open.

But the `undefined` is still missing in the ty:

```ts
getSelectedDocument(): Document;
```

**Comment by qjebbs** [comment]
There is no need to write `Document | undefined`, you can try to find out what is the type of `d`:
```ts
let d = getSelectedDocument()
function getSelectedDocument(): Document | undefined {
    return
}
```

**Comment by chpio** [comment]
your code example seems to be broken. Why is there no need to define an `undefined` return type if it's part of the return type?

**Comment by qjebbs** [comment]
@chpio  I mean, what does it help if no lint issue raised below?

```ts
let d = getSelectedDocument()
// no lint issues
console.log(d.pages)
function getSelectedDocument(): Document | undefined {
    return undefined
}
```

**Comment by chpio** [comment]
you have to enable `strictNullChecks` in `compilerOptions` in your tsconfig. They should have enabled it by default, but  i guess they refused to do so for compatibility/portability reasons with js (ts being js with *optional* types). Anyway... [NULL being the Worst Mistake in Computer Science](https://dzone.com/articles/the-worst-mistake-of-computer-science-1) should encourage you to enable `strictNullChecks` and opt-out of implicit `null` & `undefined`.

**Comment by qjebbs** [comment]
That makes sense, you are a TS expert. I'll add `| undefined` everywhere if possible, and welcome PR if you found more issues.

PS: `strictNullChecks` is not specified, and the default is false here (TS 4.1.2). I never noticed it.

**Comment by chpio** [comment]
> That makes sense, you are a TS expert.

Nah, im somewhat of an expert in rust. Rust doesn't have `null`s for exactly that reason.
