### ISSUE TITLE
There is no `layers` property on `Layer`

### ISSUE THREAD

**Issue by chpio** [qjebbs/sketch.d.ts#2]
Hi,

it seems that the `layers` property is part of [`Group`](https://developer.sketch.com/reference/api/#group) etc, but not [`Layer`](https://developer.sketch.com/reference/api/#layer) it self.

https://github.com/qjebbs/sketch.d.ts/blob/9184f4c5d4ddcf07c8898570720a6b43e7080a8e/sketch.d.ts#L770

**Comment by qjebbs** [comment]
You're right, but I'd rather take `Layer` as base type of `Group` / `Artboard` / `Page`.

```ts
function printNames(layer: Layer){
    console.log(layer.name)
    if (layer.layers && layer.layers.length)(
        layer.layers.forEach(l=>printNames(l))
    )
}
// printNames accepts Page object
printNames(context.document.pages[0])
```

and, compares with above codes, do you prefer these?:

```ts
function printNames(layer: Layer | Group | Artboard) {
    console.log(layer.name)
    switch (layer.type) {
        case sketch.Types.Artboard:
            (layer as Artboard).layers.forEach(l => printNames(l))
            break;
        case sketch.Types.Group:
            (layer as Group).layers.forEach(l => printNames(l))
            break;
        default:
            console.log(layer.name)
            break;
    }
}
printNames(context.document.pages[0])
```

**Comment by chpio** [comment]
> You're right, but I'd rather take Layer as base type of Group / Artboard / Page.

Then you should at least define it to be `layers?: Array<Layer>` on `Layer`. So that it's a build error if you forget to check for the existence of `layers`, and not your app crashing randomly at runtime. The whole point of TS is to minimize such crashes. And redefine them on classes with `layers` as it is now, best of both worlds.

----

Im doing the `instanceof`checking anyways.

```ts
function processElementFoo(layer: Group): ElementFoo {
  const children = layer.layers
     // filter by type
    .filter(createIsInstanceOf(sketch.Group))
    // filter by name
    .filter((group) => group.name.startsWith("foo"))
    // process
    .map(processElementFoo);

  return {
    name: layer.name,
    children,
  };
}

// needed to make `val is T` work seamlessly with `Array.prot.filter`
// https://github.com/Microsoft/TypeScript/issues/16069
// inspired by https://github.com/Microsoft/TypeScript/issues/16069#issuecomment-666296465
export function createIsInstanceOf<T>(klass: new () => T): (val: any) => val is T {
    return function isInstanceOf(val: any): val is T {
        return val instanceof klass;
    };
}
```

But that might just be my current project.

**Comment by qjebbs** [comment]
I'm not sure if I understand you correctly, if not, PR is welcome:

After I change the definition of `Layer.layers` to

```ts
layers?: Layer[];
```

It won't raise any lint issue if I don't check for the existence:

```ts
function printNames(layer: Layer){
    console.log(layer.name)
    // no lint issue here
    layer.layers.forEach(l=>printNames(l))
}
```

**Comment by qjebbs** [comment]
I think if `Layer.layers` of `Sketch API` returns `[]` if it's not a group solves our problem. Should we post an issue to them?
