### ISSUE TITLE
Global declaration for the "sketch" module

### ISSUE THREAD

**Issue by chpio** [qjebbs/sketch.d.ts#3]
Hi,

```ts
declare module "sketch" {
    const sketch: Sketch;
    export default sketch;
}
```

That should make imports "just" work (`import sketch from "sketch";`) no need for the awkward require (`const sketch: Sketch = require('sketch');`). Or is there a reason that would make this not possible?

**Comment by qjebbs** [comment]
@chpio PR is welcome.
