### ISSUE TITLE
Release on npm?

### ISSUE THREAD

**Issue by chpio** [qjebbs/sketch.d.ts#5]
I had problems (in an other project) with git dependencies not working correctly with npm lock files. It would also guaranty availability of the package, even it the case of you deleting or renaming the github repository.

We should be able to keep the "@types/sketch" name (~~is this actually even necessary?~~ yeap it is) by using it as an alias:

```json
"dependencies": {
  "@types/sketch": "npm:@qjebbs/sketch.d.ts@^1.0.0"
}
```

**Comment by qjebbs** [comment]
No plan about this, I've no idea about how to publish npm packages. 

I wrote the definitions only for https://github.com/qjebbs/sketch-meaxure, just publish it here to see if it helps to anyone.

If it can be done with small scripts or GitHub Action, PR is welcome.

**Comment by chpio** [comment]
just had that error in my current project. everything just works if you're working alone on a project that uses npm git deps. but fails if someone else executes `npm install`, which seem to ignore locked git deps, so that they end up using an old version of that dependency, despite the lock file saying that they need to use a newer one.

**Comment by qjebbs** [comment]
Without npm package, you can a make a copy of specific version:

https://github.com/qjebbs/sketch-meaxure/blob/c238374ec122438d968ef59ab17902eff3b2f04d/tsconfig.json#L12-L15

**Comment by chpio** [comment]
> Without npm package, you can a make a copy of specific version:
> 
> https://github.com/qjebbs/sketch-meaxure/blob/c238374ec122438d968ef59ab17902eff3b2f04d/tsconfig.json#L12-L15

Im not sure what you mean by that. are you referring to vendoring?

----

ive released it by myself <https://www.npmjs.com/package/@chpio/sketch>. releasing an npm pkg is quite easy, you need to execute `npm publish` and that version get packaged and uploaded to npm. but there are a few other changes in my git fork, like letting npm upload just the needed files.

**Comment by qjebbs** [comment]
good to hear
